services:

    zk2.sps:
        class: Zk2\SpsBundle\Model\SpsService
        arguments:
            - '@request_stack'
            - '@form.factory'
            - '@router'
            - '@zk2.sps.form_filter.serializer'
            - '%zk2_sps.session_key%'

    zk2.sps.twig_extension:
        class: Zk2\SpsBundle\Twig\Extension\SpsExtension
        public: false
        arguments: [null, '%zk2_sps.templates%']
        tags:
            -  { name: twig.extension }

    zk2.sps.form_filter.serializer:
        class: Zk2\SpsBundle\Utils\FormFilterSerializer
        arguments: ['@doctrine', '@session']


    # form type

    zk2.sps.date_bootstrap.type:
        class:  Zk2\SpsBundle\Form\Type\DateBootstrapType
        arguments: ['%locale%']
        tags:
            - { name: form.type, alias: zk2_sps_date_bootstrap_type }

    zk2.sps.date_range_bootstrap.type:
        class:  Zk2\SpsBundle\Form\Type\DateRangeBootstrapType
        arguments: ['%locale%', true]
        tags:
            - { name: form.type, alias: zk2_sps_date_range_bootstrap_type }

    zk2.sps.date.filter.type:
        class:  Zk2\SpsBundle\Form\Filter\DateFilterType
        tags:
            - { name: form.type, alias: zk2_sps_date_filter_type }

    zk2.sps.date_range.filter.type:
        class:  Zk2\SpsBundle\Form\Filter\DateRangeFilterType
        tags:
            - { name: form.type, alias: zk2_sps_date_range_filter_type }

    zk2.sps.string.filter.type:
        class:  Zk2\SpsBundle\Form\Filter\StringFilterType
        tags:
            - { name: form.type, alias: zk2_sps_string_filter_type }

    zk2.sps.numeric.filter.type:
        class:  Zk2\SpsBundle\Form\Filter\NumericFilterType
        tags:
            - { name: form.type, alias: zk2_sps_numeric_filter_type }

    zk2.sps.choice.filter.type:
        class:  Zk2\SpsBundle\Form\Filter\ChoiceFilterType
        tags:
            - { name: form.type, alias: zk2_sps_choice_filter_type }

    zk2.sps.boolean.filter.type:
        class:  Zk2\SpsBundle\Form\Filter\BooleanFilterType
        tags:
            - { name: form.type, alias: zk2_sps_boolean_filter_type }
